# Generated by Django 5.1.6 on 2025-02-07 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["-points"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["name"], "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Grade must be one of the following: A, A-, B+, B, B-, C+, C, C-, D+, D, D-, E",
                        regex="^(A|A-|B\\+|B|B-|C\\+|C|C-|D\\+|D|D-|E)$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="points",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ]
            ),
        ),
    ]
