# Generated by Django 5.1.6 on 2025-02-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0002_alter_grade_options_alter_subject_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("detail", models.TextField()),
                ("image_url", models.URLField(max_length=500)),
            ],
            options={
                "verbose_name_plural": "universities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("course_count", models.PositiveIntegerField(default=0)),
                ("main_courses", models.JSONField(default=list)),
                ("university_established", models.PositiveIntegerField()),
                (
                    "universityList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="eduapp.universitylist",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("universityList", "name")},
            },
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("cluster_points", models.DecimalField(decimal_places=2, max_digits=5)),
                ("details", models.TextField()),
                ("requirements", models.TextField()),
                ("university_name", models.CharField(max_length=200)),
                ("university_image", models.URLField(max_length=500)),
                (
                    "universityList",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course",
                        to="eduapp.universitylist",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("university_name", "name")},
            },
        ),
    ]
