# Generated by Django 5.1.6 on 2025-02-12 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0003_universitylist_schooldetail_courses"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courses",
            unique_together={("universityList", "name")},
        ),
        migrations.RemoveField(
            model_name="courses",
            name="university_name",
        ),
    ]
