# Generated by Django 5.1.6 on 2025-02-12 06:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0004_alter_courses_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
