# Generated by Django 5.1.6 on 2025-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0005_alter_courses_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("university_established", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="SchoolDetail",
        ),
    ]
