# Generated by Django 5.1.6 on 2025-02-24 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0006_coursedetail_delete_schooldetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="cluster_points",
        ),
        migrations.RemoveField(
            model_name="courses",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="courses",
            name="university_image",
        ),
        migrations.AddField(
            model_name="courses",
            name="coursecode",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CourseRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subjects", models.TextField()),
                (
                    "cluster_wights21",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "cluster_wights22",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eduapp.courses"
                    ),
                ),
            ],
        ),
    ]
