# Generated by Django 5.1.6 on 2025-02-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0007_remove_courses_cluster_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="coursecode",
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
