# Generated by Django 5.1.6 on 2025-02-25 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0008_alter_courses_coursecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="details",
            field=models.TextField(default="tttt"),
        ),
        migrations.AlterField(
            model_name="courses",
            name="details",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="eduapp.coursedetail",
            ),
        ),
    ]
