# Generated by Django 5.1.6 on 2025-02-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0009_coursedetail_details_alter_courses_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eduapp.coursedetail",
            ),
        ),
    ]
