# Generated by Django 5.1.6 on 2025-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0010_alter_courses_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="details",
            field=models.TextField(default="tttt"),
        ),
    ]
