# Generated by Django 5.1.6 on 2025-02-25 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0011_alter_courses_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courses",
            name="details",
        ),
    ]
