# Generated by Django 5.1.6 on 2025-02-26 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0013_courses_details"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courses",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="courses",
            name="details",
        ),
        migrations.RemoveField(
            model_name="courses",
            name="universityList",
        ),
        migrations.DeleteModel(
            name="CourseRequirement",
        ),
        migrations.DeleteModel(
            name="Courses",
        ),
    ]
