# Generated by Django 5.1.6 on 2025-03-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eduapp",
            "0014_alter_courses_unique_together_remove_courses_details_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetail",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coursecode", models.PositiveIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("cf_2021", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cf_2022", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduapp.coursedetail",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduapp.universitylist",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("code", "name")},
            },
        ),
    ]
