# Generated by Django 5.1.6 on 2025-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0015_alter_coursedetail_name_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="coursecode",
            field=models.BigIntegerField(unique=True),
        ),
    ]
