# Generated by Django 5.1.6 on 2025-04-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0016_alter_course_coursecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cf_2021",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name="course",
            name="cf_2022",
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
