# Generated by Django 5.1.6 on 2025-04-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduapp", "0017_alter_course_cf_2021_alter_course_cf_2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="requirement",
            field=models.CharField(default="ttt", max_length=200),
        ),
    ]
